### ISSUE TITLE
`loadSDLTTF()` always return `badLibrary`

### ISSUE THREAD

**Issue by rodevasia** [BindBC/bindbc-sdl#76]
Is this still on development?, should I be wait until a stable release has to come.

I have installed the pre-release version 3.1.0 of SDL_TTF.

```json
	"versions": [
		"SDL_MainUseCallbacks",
		"SDL_TTF_3_0"
	]
```

**Comment by ichordev** [comment]
> I have installed the pre-release version 3.1.0 of SDL_TTF.

That is the wrong version. Like it says in the readme, this is the supported SDL_ttf commit: https://github.com/libsdl-org/SDL_ttf/commit/205290043e82bd19b9c50514787c65d574724d4f

Pre-release 3.1.0 is **not** ABI compatible with that commit. Pre-release 3.1.0 came out after the current version of the bindings. I will update the bindings to support pre-release 3.1.0 later.

**Comment by ichordev** [comment]
I just released BindBC-SDL 2.1.0 which now supports SDL_ttf pre-release 3.1.

**Comment by rodevasia** [comment]
I still can't get this work.
Am I missing something?

```bash
$ git log -1 --format=%H
```
```
07e4d1241817f2c0f81749183fac5ec82d7bbd72
```
```bash 
 $ locate SDL3_ttf | grep -v "/home/username"
```
```
/usr/local/include/SDL3_ttf
/usr/local/include/SDL3_ttf/SDL_textengine.h
/usr/local/include/SDL3_ttf/SDL_ttf.h
/usr/local/lib/libSDL3_ttf.so
/usr/local/lib/libSDL3_ttf.so.0
/usr/local/lib/libSDL3_ttf.so.0.1.0
/usr/local/lib/cmake/SDL3_ttf
/usr/local/lib/cmake/SDL3_ttf/Findharfbuzz.cmake
/usr/local/lib/cmake/SDL3_ttf/Findplutosvg.cmake
/usr/local/lib/cmake/SDL3_ttf/PkgConfigHelper.cmake
/usr/local/lib/cmake/SDL3_ttf/SDL3_ttf-shared-targets-debug.cmake
/usr/local/lib/cmake/SDL3_ttf/SDL3_ttf-shared-targets.cmake
/usr/local/lib/cmake/SDL3_ttf/SDL3_ttfConfig.cmake
/usr/local/lib/cmake/SDL3_ttf/SDL3_ttfConfigVersion.cmake
/usr/local/share/licenses/SDL3_ttf
/usr/local/share/licenses/SDL3_ttf/LICENSE.txt

```

my build commands:

```
mkdir build && cd build
cmake ..
make
sudo make install
```

`dub.json`

```json
"dependencies": {
	"bindbc-sdl": "~>2.1.0"
	},
"versions": [
	"SDL3",
	"SDL_TTF_3_1"
	]
```

`dub.selections.json`

```json
{
	"fileVersion": 1,
	"versions": {
		"bindbc-common": "1.0.5",
		"bindbc-loader": "1.1.5",
		"bindbc-sdl": "2.1.0"
	}
}

```

**Comment by ichordev** [comment]
> I still can't get this work. Am I missing something?

What exactly is happening? If your code is compiling and you're still getting `badLibrary`, could you please provide the error messages from bindbc.loader? It is possible that you don't have `/usr/local/lib` in your library path.

> my build commands:
> 
> ```
> mkdir build && cd build
> cmake ..
> make
> sudo make install
> ```

Build commands for what?

**Comment by ichordev** [comment]
> LoadMsg ttf = loadSDLTTF();
> 
>     if (ttf != LoadMsg.success)
>     {
>         writeln("Failed to load SDL_TTF: ", ttf);
>         return;
>     }
>  [ FlexD ] $ dub run --config=flexd
> Starting Performing "debug" build using /usr/bin/dmd for x86_64. Up-to-date bindbc-common 1.0.5: target for configuration [noBC] is up to date. Up-to-date bindbc-loader 1.1.5: target for configuration [noBC] is up to date. Up-to-date bindbc-sdl 2.1.0: target for configuration [dynamic] is up to date. Building flexd ~master: building configuration [flexd] Linking flexd Finished To force a rebuild of up-to-date targets, run again with --force Running bin/flexd/flexd Failed to load SDL_TTF: badLibrary

Please print error messages from bindbc.loader:

```d

LoadMsg ret = loadSDL();
if(ret != LoadMsg.success){
	import std.string: fromStringz;
	import loader = bindbc.loader.sharedlib;
	foreach(info; loader.errors){
		writeln(info.error.fromStringz,", ",info.message.fromStringz);
	}
}
```

> the build command I provided is for building SDL_ttf library.

That is irrelevant to this issue.

**Comment by rodevasia** [comment]
Missing Symbol, TTF_GetTextProperties

**Comment by ichordev** [comment]
> Missing Symbol, TTF_GetTextProperties

Well, [that symbol should exist in preview-3.1.0](https://github.com/libsdl-org/SDL_ttf/blob/07e4d1241817f2c0f81749183fac5ec82d7bbd72/include/SDL3_ttf/SDL_ttf.h#L1993). The git hash you showed matches preview-3.1.0 which is good. Could you please make sure that your `libSDL3_ttf.so` exports the symbol `TTF_GetTextProperties` using `nm /usr/local/lib/libSDL3_ttf.so | grep TTF_GetTextProperties`?

**Comment by rodevasia** [comment]
```bash
[ ~ ] $ nm /usr/local/lib/libSDL3_ttf.so | grep TTF_GetTextProperties
00000000000211c9 t TTF_GetTextProperties
```

**Comment by ichordev** [comment]
> [ ~ ] $ nm /usr/local/lib/libSDL3_ttf.so | grep TTF_GetTextProperties
> 00000000000211c9 t TTF_GetTextProperties

Seems like everything is fine. It really should be working. Are you positive that you don’t have another version of the library installed somewhere?
